export default [
  {
    id: 1,
    img: "https://picsum.photos/300/200",
    title: "mem1",
    upvotes: "",
    downvotes: "",
  },
  {
    id: 2,
    img: "https://picsum.photos/301/200",
    title: "mem2",
    upvotes: "",
    downvotes: "",
  },
  {
    id: 3,
    img: "https://picsum.photos/302/200",
    title: "mem3",
    upvotes: "",
    downvotes: "",
  },
  {
    id: 4,
    img: "https://picsum.photos/303/200",
    title: "mem4",
    upvotes: "",
    downvotes: "",
  },
  {
    id: 5,
    img: "https://picsum.photos/304/200",
    title: "mem5",
    upvotes: "",
    downvotes: "",
  },
  {
    id: 6,
    img: "https://picsum.photos/305/200",
    title: "mem6",
    upvotes: "",
    downvotes: "",
  },
  {
    id: 7,
    img: "https://picsum.photos/306/200",
    title: "mem7",
    upvotes: "",
    downvotes: "",
  },
  {
    id: 8,
    img: "https://picsum.photos/300/201",
    title: "mem8",
    upvotes: "",
    downvotes: "",
  },
  {
    id: 9,
    img: "https://picsum.photos/300/202",
    title: "mem9",
    upvotes: "",
    downvotes: "",
  },
  {
    id: 10,
    img: "https://picsum.photos/300/203",
    title: "mem10",
    upvotes: "",
    downvotes: "",
  },
  {
    id: 11,
    img: "https://picsum.photos/300/204",
    title: "mem11",
    upvotes: "",
    downvotes: "",
  },
  {
    id: 12,
    img: "https://picsum.photos/300/205",
    title: "mem12",
    upvotes: "",
    downvotes: "",
  },
];
